# Generated by Django 3.0.5 on 2020-05-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200514_0652'),
        ('postjob', '0003_auto_20200514_0952'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'user')},
        ),
    ]
